---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecurityAudit
      - arn:aws:iam::aws:policy/AmazonInspectorReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: 
            - !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref ZCwpAwsAccountNumber
                - ':root'
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalId
  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: RadwareCWPReadOnlyAccess
      Roles:
      - Ref: Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ListBuckets
          Action: 
          - s3:ListBucket
          Effect: Allow
          Resource: 
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketFlowLogs
              - '/'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketFlowLogs
              - '/*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketCloudTrail
              - '/'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketCloudTrail
              - '/*'
        - Sid: ReadLogs
          Action:
          - s3:Get*
          Effect: Allow
          Resource: 
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketFlowLogs
              - '/AWSLogs/'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketFlowLogs
              - '/AWSLogs/*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketCloudTrail
              - '/AWSLogs/'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3BucketCloudTrail
              - '/AWSLogs/*'
        - Sid: RadwareCWPReadOnlyAccess
          Action:
          - logs:GetLogEvents
          - logs:FilterLogEvents
          - s3:ListBucket
          - sns:ListSubscriptions
          - elasticfilesystem:DescribeTags
          - dynamodb:ListTagsOfResource
          - wafv2:ListResourcesForWebACL
          - wafv2:ListWebACLs
          - waf-regional:ListResourcesForWebACL
          Effect: Allow
          Resource: "*"
Parameters:
  ExternalId:
    Type: String
    Description: 'Enter External ID for Radware CWP Role (mininum length: 8) (e.g. a1b2c3d4e5f6)'
    MinLength: 8
  S3BucketFlowLogs:
    Type: String
    Default: s3BucketName</optionalPrefix>
    Description: 'Enter S3 bucket name for VPC FlowLogs (e.g. mybucketname/myprefix)'
    MinLength: 3
  S3BucketCloudTrail:
    Type: String
    Default: s3BucketName</optionalPrefix>
    Description: 'Enter S3 bucket name for CloudTrail (e.g. mybucketname/myprefix)'
    MinLength: 3
  S3BucketCloudTrail:
    Type: String
    Default: s3BucketName</optionalPrefix>
    Description: 'Enter S3 bucket name for CloudTrail (e.g. mybucketname/myprefix)'
    MinLength: 3
  ZCwpAwsAccountNumber:
    Type: String
    Default: 342443945406
    Description: 'CWP AWS Account Number. DO NOT CHANGE - Advanced users only'
    MinLength: 12
Outputs:
  RoleARNID:
    Description: Your Role ARN ID
    Value:
      Fn::GetAtt:
      - Role
      - Arn
  ExternalId:
    Description: Your External ID
    Value:
      Ref: ExternalId